const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      ratting: 4.0,
      numReviews: 10,
      description: 'High Quality Product',
    },

    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      ratting: 4.0,
      numReviews: 10,
      description: 'High Quality Product',
    },

    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      ratting: 4.0,
      numReviews: 10,
      description: 'High Quality Product',
    },

    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      ratting: 4.0,
      numReviews: 10,
      description: 'High Quality Product',
    },
  ],
};
